pipeline {
  agent any
  stages {
    stage('Log Ant version info') {
      steps {
        
      }
    }
    stage('GitHub Jenkins Ant Build') {
      steps {
        git 'https://github.com/btharabai/LearnGIT.git'
      }
    }
  }
}
