pipeline {
    agent any
    tools {
        maven "mavenhome"
    }

    stages {
        stage('Checkout The Sourcecode') {
            steps {
                echo 'checkout the Source code form the github'
                git 'https://github.com/btharabai/LearnGIT.git'
            }
        }
        stage('Compile'){
            steps{
                echo 'Compilation of the source code'
                bat 'mvn -f DevOpsClassCodes-master/pom.xml compile'
            }
        }
        stage('Test'){
            steps{
                 echo 'Testing of the source code'
                 bat 'mvn -f DevOpsClassCodes-master/pom.xml test'
            }
        }
        stage('QA'){
            steps{
                 echo 'QA of the source code'
                 bat 'mvn -f DevOpsClassCodes-master/pom.xml pmd:pmd'
            }
        }
        stage('Package'){
            steps{
                 echo 'Package the source code'
                 bat 'mvn -f DevOpsClassCodes-master/pom.xml package'
                
            }
        }
    }
}
